name: deploymentManifest
director_uuid: AADSC-1234
instance-groups:
- name: testInstance
  instances: 8
  azs:
  - z1
  - z2
  jobs:
  - name: redis-server
    release: redis
    consumes: {}
    provides: {}
    properties:
      port: 3606
  vm_type: minimal
  vm_extensions: []
  vm_resources:
    cpu: 2
    ram: 2048
    ephemeral_disk_size: 4096
  stemcell: ""
  persistent_disk: 0
  persistent_disk_type: ""
  networks:
  - name: default
    static_ips: []
    default: []
  update:
    canaries: 0
    max_in_flight: ""
    canary_watch_time: ""
    update_watch_time: ""
    serial: false
    vm_stratergy: ""
  migrated_from:
    name: ""
    az: ""
  lifecycle: errand
  properties: {}
  env:
    persistent_disk_fs: ""
    persistent_disk_mount_options: []
    bosh:
      password: ""
      keep_root_password: ""
      remove_dev_tools: false
      remove_static_libraries: false
      swap_size: 0
      ipv6:
        enable: false
      job_dir:
        tmpfs: false
        tmpfs_size: ""
      agent:
        settings: ""
        tmpfs: false
features:
  converge_variables: false
  randomize_az_placement: false
  use_dns_addresses: true
tags:
  project: cf
releases:
- name: redis
  version: "12"
  url: ""
  sha1: ""
  stemcell:
    alias: ""
    os: ""
    version: ""
    name: ""
stemcells:
- alias: default
  os: ubuntu-trusty
  version: "3147"
  name: ""
addons: []
properties: []
variables: []
update:
  canaries: 0
  max_in_flight: ""
  canary_watch_time: ""
  update_watch_time: ""
  serial: false
  vm_stratergy: ""
